"""
Stage 3 Challenge: Deep Learning, Local LLMs & Enterprise RAG
Gate 3 Focus: Vector Similarity, Semantic Chunking & Citation Grounding (Project P2)
"""
import math
from typing import List, Dict, Any

class VectorSearchEngine:
    """
    In-memory cosine similarity search ranker for vector embeddings.
    """
    @staticmethod
    def cosine_similarity(vec_a: List[float], vec_b: List[float]) -> float:
        if len(vec_a) != len(vec_b) or not vec_a:
            return 0.0
        dot = sum(a * b for a, b in zip(vec_a, vec_b))
        norm_a = math.sqrt(sum(a * a for a in vec_a))
        norm_b = math.sqrt(sum(b * b for b in vec_b))
        if norm_a == 0.0 or norm_b == 0.0:
            return 0.0
        return dot / (norm_a * norm_b)

    def rank(self, query_vec: List[float], documents: List[Dict[str, Any]], top_k: int = 2) -> List[Dict[str, Any]]:
        scored = []
        for doc in documents:
            sim = self.cosine_similarity(query_vec, doc["embedding"])
            item = dict(doc)
            item["score"] = round(sim, 4)
            scored.append(item)
        scored.sort(key=lambda x: x["score"], reverse=True)
        return scored[:top_k]


class CitationGroundingValidator:
    """
    Validates whether an answer generated by an LLM is grounded in provided evidence chunks.
    """
    @staticmethod
    def validate_grounding(answer: str, context_chunks: List[str]) -> bool:
        # Check if the factual keywords of the answer exist in context
        words = [w.strip(".,;:?!") for w in answer.lower().split() if len(w) > 3]
        if not words:
            return False
        combined_context = " ".join(context_chunks).lower()
        matched = sum(1 for w in words if w in combined_context)
        return (matched / len(words)) >= 0.70
